version: '3'

services:
  mongodb:
    image: 
      mongo: latest
      container_name: mongodb
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INIT_ROOT_PASSWORD: 1234
        MONGO_INIT_DATABASE: gestaoDeGastos
      ports:
        - 27017:27017


jenkins:
  build: .
  ports:
    - "8080:8080"
    - "50000:50000"
  volumes:
    - ./jenkins_home:/var/jenkins_home